//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeeTrayTOTP.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeeTrayTOTP.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTP.
        /// </summary>
        internal static string ColumnTOTPCode {
            get {
                return ResourceManager.GetString("ColumnTOTPCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTP Status.
        /// </summary>
        internal static string ColumnTOTPStatus {
            get {
                return ResourceManager.GetString("ColumnTOTPStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed!.
        /// </summary>
        internal static string ConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy TOTP.
        /// </summary>
        internal static string CopyTOTP {
            get {
                return ResourceManager.GetString("CopyTOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database is locked!.
        /// </summary>
        internal static string DatabaseIsLocked {
            get {
                return ResourceManager.GetString("DatabaseIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database is not open!.
        /// </summary>
        internal static string DatabaseIsNotOpen {
            get {
                return ResourceManager.GetString("DatabaseIsNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, bad seed!.
        /// </summary>
        internal static string ErrorBadSeed {
            get {
                return ResourceManager.GetString("ErrorBadSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, bad settings!.
        /// </summary>
        internal static string ErrorBadSettings {
            get {
                return ResourceManager.GetString("ErrorBadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, no seed!.
        /// </summary>
        internal static string ErrorNoSeed {
            get {
                return ResourceManager.GetString("ErrorNoSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        internal static string Locked {
            get {
                return ResourceManager.GetString("Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No database is opened!.
        /// </summary>
        internal static string NoDatabaseIsOpened {
            get {
                return ResourceManager.GetString("NoDatabaseIsOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No TOTP Entries found.
        /// </summary>
        internal static string NoTOTPEntriesFound {
            get {
                return ResourceManager.GetString("NoTOTPEntriesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No TOTP Seed found!.
        /// </summary>
        internal static string NoTOTPSeedFound {
            get {
                return ResourceManager.GetString("NoTOTPSeedFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset all the settings to their default values?.
        /// </summary>
        internal static string SettingsAskResetDefaultValues {
            get {
                return ResourceManager.GetString("SettingsAskResetDefaultValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The currently opened database is locked! This function only works with an unlocked database..
        /// </summary>
        internal static string SettingsCurrentDatabaseLocked {
            get {
                return ResourceManager.GetString("SettingsCurrentDatabaseLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings restored to defaults!.
        /// </summary>
        internal static string SettingsDefaultValuesRestored {
            get {
                return ResourceManager.GetString("SettingsDefaultValuesRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please start by enabling &quot;Field rename&quot;..
        /// </summary>
        internal static string SettingsEnableFieldRename {
            get {
                return ResourceManager.GetString("SettingsEnableFieldRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors detected!.
        /// </summary>
        internal static string SettingsErrors {
            get {
                return ResourceManager.GetString("SettingsErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character!.
        /// </summary>
        internal static string SettingsInvalidCharacter {
            get {
                return ResourceManager.GetString("SettingsInvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid name! Must be different than the Seed String..
        /// </summary>
        internal static string SettingsInvalidNameSeed {
            get {
                return ResourceManager.GetString("SettingsInvalidNameSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid name! Must be different than the Setting String..
        /// </summary>
        internal static string SettingsInvalidNameSetting {
            get {
                return ResourceManager.GetString("SettingsInvalidNameSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning, no internet connection detected!{0}{0}You will not be able to add any server until you are connected..
        /// </summary>
        internal static string SettingsNoInternetDetected {
            get {
                return ResourceManager.GetString("SettingsNoInternetDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have an opened database in order to use this function..
        /// </summary>
        internal static string SettingsOpenDatabaseRequired {
            get {
                return ResourceManager.GetString("SettingsOpenDatabaseRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        internal static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes the current TOTP settings..
        /// </summary>
        internal static string SetupDelete {
            get {
                return ResourceManager.GetString("SetupDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes the wizard..
        /// </summary>
        internal static string SetupFinish {
            get {
                return ResourceManager.GetString("SetupFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval must be between{0}nand 180 inclusively!.
        /// </summary>
        internal static string SetupInterval {
            get {
                return ResourceManager.GetString("SetupInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character.
        /// </summary>
        internal static string SetupInvalidCharacter {
            get {
                return ResourceManager.GetString("SetupInvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padding (=) can only appear at the end!.
        /// </summary>
        internal static string SetupInvalidPadding {
            get {
                return ResourceManager.GetString("SetupInvalidPadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL!.
        /// </summary>
        internal static string SetupInvalidUrl {
            get {
                return ResourceManager.GetString("SetupInvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length is mandatory!.
        /// </summary>
        internal static string SetupLengthMandatory {
            get {
                return ResourceManager.GetString("SetupLengthMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the current entry&apos;s TOTP settings?.
        /// </summary>
        internal static string SetupMessageAskDeleteCurrentEntry {
            get {
                return ResourceManager.GetString("SetupMessageAskDeleteCurrentEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seed cannot be empty!.
        /// </summary>
        internal static string SetupSeedCantBeEmpty {
            get {
                return ResourceManager.GetString("SetupSeedCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup TOTP.
        /// </summary>
        internal static string SetupTOTP {
            get {
                return ResourceManager.GetString("SetupTOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show QR.
        /// </summary>
        internal static string ShowQR {
            get {
                return ResourceManager.GetString("ShowQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/KeeTrayTOTP/KeeTrayTOTP/issues.
        /// </summary>
        internal static string SupportUrl {
            get {
                return ResourceManager.GetString("SupportUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to {0}.
        /// </summary>
        internal static string SwitchTo {
            get {
                return ResourceManager.GetString("SwitchTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection to the server failed..
        /// </summary>
        internal static string TcConnectionFailed {
            get {
                return ResourceManager.GetString("TcConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait, verifying....
        /// </summary>
        internal static string TcPleaseWaitVerifying {
            get {
                return ResourceManager.GetString("TcPleaseWaitVerifying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        internal static string TcSucces {
            get {
                return ResourceManager.GetString("TcSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing URL!.
        /// </summary>
        internal static string TcUrlExists {
            get {
                return ResourceManager.GetString("TcUrlExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL!.
        /// </summary>
        internal static string TcUrlInvalid {
            get {
                return ResourceManager.GetString("TcUrlInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL must contain &quot;http&quot;!.
        /// </summary>
        internal static string TcUrlMustContainHttp {
            get {
                return ResourceManager.GetString("TcUrlMustContainHttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification cancelled!.
        /// </summary>
        internal static string TcVerificationCancelled {
            get {
                return ResourceManager.GetString("TcVerificationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Correction.
        /// </summary>
        internal static string TimeCorrection {
            get {
                return ResourceManager.GetString("TimeCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTP.
        /// </summary>
        internal static string TOTP {
            get {
                return ResourceManager.GetString("TOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTP Enabled.
        /// </summary>
        internal static string TOTPEnabled {
            get {
                return ResourceManager.GetString("TOTPEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTP Seed.
        /// </summary>
        internal static string TOTPSeed {
            get {
                return ResourceManager.GetString("TOTPSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTP Settings.
        /// </summary>
        internal static string TOTPSettings {
            get {
                return ResourceManager.GetString("TOTPSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tray TOTP Plugin.
        /// </summary>
        internal static string TrayTOTPPlugin {
            get {
                return ResourceManager.GetString("TrayTOTPPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning, bad URL?.
        /// </summary>
        internal static string WarningBadURL {
            get {
                return ResourceManager.GetString("WarningBadURL", resourceCulture);
            }
        }
    }
}
