//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeeTrayTOTP {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FormSettings_Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormSettings_Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeeTrayTOTP.FormSettings_Localization", typeof(FormSettings_Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset all the settings to their default values?.
        /// </summary>
        internal static string SettingsAskResetDefaultValues {
            get {
                return ResourceManager.GetString("SettingsAskResetDefaultValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The currently opened database is locked! This function only works with an unlocked database..
        /// </summary>
        internal static string SettingsCurrentDatabaseLocked {
            get {
                return ResourceManager.GetString("SettingsCurrentDatabaseLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings restored to defaults!.
        /// </summary>
        internal static string SettingsDefaultValuesRestored {
            get {
                return ResourceManager.GetString("SettingsDefaultValuesRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please start by enabling &quot;Field rename&quot;..
        /// </summary>
        internal static string SettingsEnableFieldRename {
            get {
                return ResourceManager.GetString("SettingsEnableFieldRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors detected!.
        /// </summary>
        internal static string SettingsErrors {
            get {
                return ResourceManager.GetString("SettingsErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character!.
        /// </summary>
        internal static string SettingsInvalidCharacter {
            get {
                return ResourceManager.GetString("SettingsInvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid name! Must be different than the Seed String..
        /// </summary>
        internal static string SettingsInvalidNameSeed {
            get {
                return ResourceManager.GetString("SettingsInvalidNameSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid name! Must be different than the Setting String..
        /// </summary>
        internal static string SettingsInvalidNameSetting {
            get {
                return ResourceManager.GetString("SettingsInvalidNameSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning, no internet connection detected!{0}{0}You will not be able to add any server until you are connected..
        /// </summary>
        internal static string SettingsNoInternetDetected {
            get {
                return ResourceManager.GetString("SettingsNoInternetDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have an opened database in order to use this function..
        /// </summary>
        internal static string SettingsOpenDatabaseRequired {
            get {
                return ResourceManager.GetString("SettingsOpenDatabaseRequired", resourceCulture);
            }
        }
    }
}
