//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeeTrayTOTP {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SetupTOTP_Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SetupTOTP_Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeeTrayTOTP.SetupTOTP_Localization", typeof(SetupTOTP_Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes the current TOTP settings..
        /// </summary>
        internal static string SetupDelete {
            get {
                return ResourceManager.GetString("SetupDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes the wizard..
        /// </summary>
        internal static string SetupFinnish {
            get {
                return ResourceManager.GetString("SetupFinnish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval must be between{0}nand 60 inclusively!.
        /// </summary>
        internal static string SetupInterval1to60 {
            get {
                return ResourceManager.GetString("SetupInterval1to60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character.
        /// </summary>
        internal static string SetupInvalidCharacter {
            get {
                return ResourceManager.GetString("SetupInvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL!.
        /// </summary>
        internal static string SetupInvalidUrl {
            get {
                return ResourceManager.GetString("SetupInvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length is mandatory!.
        /// </summary>
        internal static string SetupLengthMandatory {
            get {
                return ResourceManager.GetString("SetupLengthMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the current entry&apos;s TOTP settings?.
        /// </summary>
        internal static string SetupMessageAskDeleteCurrentEntry {
            get {
                return ResourceManager.GetString("SetupMessageAskDeleteCurrentEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next step..
        /// </summary>
        internal static string SetupNext {
            get {
                return ResourceManager.GetString("SetupNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous step..
        /// </summary>
        internal static string SetupPrevious {
            get {
                return ResourceManager.GetString("SetupPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create or applies changes to the current entry&apos;s TOTP Settings..
        /// </summary>
        internal static string SetupProceed {
            get {
                return ResourceManager.GetString("SetupProceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seed cannot be empty!.
        /// </summary>
        internal static string SetupSeedCantBeEmpty {
            get {
                return ResourceManager.GetString("SetupSeedCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL must include &quot;http&quot;!.
        /// </summary>
        internal static string SetupUrlMustContainHttp {
            get {
                return ResourceManager.GetString("SetupUrlMustContainHttp", resourceCulture);
            }
        }
    }
}
