name: "KeeTrayTOTP Tagged Release"

# Trigger on tags starting with v
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1

    - name: nuget restore
      run: nuget restore KeeTrayTOTP.sln

    - name: MSBuild (With Plgx)
      run: msbuild KeeTrayTOTP.sln /p:Configuration=ReleasePlgx

    - name: Upload plgx
      uses: actions/upload-artifact@v1
      with:
        name: KeeTrayTOTP.plgx
        path: KeeTrayTOTP\bin\ReleasePlgx\KeeTrayTOTP.plgx

    - name: Create release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
           **/KeeTrayTOTP.plgx
