name: "KeeTrayTOTP Tagged Release"

# Trigger on tags starting with v
on:
  push:
    tags:
      - "v*"

env:
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0
    
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1

    - name: nuget restore
      run: nuget restore KeeTrayTOTP.sln

    - name: MSBuild (With Plgx)
      run: msbuild KeeTrayTOTP.sln /p:Configuration=ReleasePlgx

    - name: Upload plgx
      uses: actions/upload-artifact@v1
      with:
        name: KeeTrayTOTP.plgx
        path: KeeTrayTOTP\bin\ReleasePlgx\KeeTrayTOTP.plgx

    - name: Generate hashes
      run: |
        Add-Content hashes.txt "Filename: KeeTrayTOTP.plgx"
        Add-Content hashes.txt "=========================="
        foreach ($algorithm in (Get-Command Get-FileHash).Parameters["Algorithm"].Attributes[1].ValidValues)
        {
            Add-Content hashes.txt "${algorithm}: $((Get-FileHash KeeTrayTOTP\bin\ReleasePlgx\KeeTrayTOTP.plgx -Algorithm $algorithm).Hash)"
        }
      shell: pwsh

    - name: Create release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
           **/KeeTrayTOTP.plgx
           hashes.txt
